### ISSUE TITLE
Switch to relative routing

### ISSUE THREAD

**Issue by delianides** [NewSpring/perrynoble.com#1]
Most routing seems to be hard-coded to https://perrynoble.com. This will affect local development. Links and paths need to be relative to whatever the hostname might be.

**Comment by delianides** [comment]
@briankalwat

**Comment by briankalwat** [comment]
@delianides I can work on changing it tomorrow. It should be using {path='page'} if it isn't already.

**Comment by briankalwat** [comment]
@delianides I've updated the only things that I could find that aren't using {path=''}.
